[tools]
golang = "1.25.5"
"go:github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb" = "v0.6.0"
"go:github.com/yannh/kubeconform/cmd/kubeconform" = "v0.7.0"
"go:github.com/mikefarah/yq/v4" = "v4.49.1"
"go:github.com/google/go-jsonnet/cmd/jsonnet" = "v0.21.0"
"go:github.com/google/go-jsonnet/cmd/jsonnet-lint" = "v0.21.0"

[tasks.lint]
description = "Run linters"
run = ["./scripts/lint.sh"]
