apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: media-center
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: media
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: shino
      securityContext:
        supplementalGroups:
          - 999
        fsGroup: 999
      initContainers:
        - name: chown
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: plex-config
              mountPath: /data/config
            - name: media
              mountPath: /data/media
          command:
            - sh
            - -c
            - (chmod 0775 /data/*; chgrp 999 /data/*; exit 0)
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          persistentVolumeClaim:
            claimName: media-storage
        - name: dri
          hostPath:
            path: /dev/dri
        # Temp Dirs
        - name: transcoding
          emptyDir: {}
      containers:
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
            - name: VERSION
              value: "docker"
          livenessProbe:
            httpGet:
              path: /identity
              port: plex-http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /identity
              port: plex-http
          ports:
            - containerPort: 32400
              name: plex-http
              hostPort: 32400
              protocol: TCP
            - containerPort: 32400
              name: plex-http-udp
              hostPort: 32400
              protocol: UDP
            - containerPort: 32469
              hostPort: 32469
              protocol: TCP
            - containerPort: 32469
              protocol: UDP
              hostPort: 32469
            - containerPort: 5353
              hostPort: 5353
              protocol: UDP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: media
              mountPath: /data/media
            - name: transcoding
              mountPath: /transcoding
            - name: dri
              mountPath: /dev/dri
          resources:
            requests:
              cpu: 2
              memory: 3Gi
            limits:
              cpu: 8
              memory: 5Gi
