apiVersion: v2
name: jsonnet-dev
description: Jsonnet Playground, based on go playground
sources:
  - https://github.com/rgst-io/jsonnet-playground
type: application
version: 0.1.2
appVersion: "1.0.2"
maintainers:
  - email: jared@rgst.io
    name: jaredallard
dependencies:
  - name: postgres
    version: "1.4.3"
    repository: https://groundhog2k.github.io/helm-charts/
